### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by gtigas** [gtigas/farcebook#26]

**Comment by gtigas** [comment]
- Users can sign up and sign in
- Preloaded state remembers current user if logged in
- Errors pop up on incorrect session login
- Complete styling

**Comment by mfeniseycopes** [comment]
Looks good, though the errors are incorrect. First/last name are highlighted, but not listed in errors and I get some duplicate errors after fixing and resubmitting.

**Comment by gtigas** [comment]
@mfeniseycopes ✔️ Fixed highlighting and clearing errors on new submission.

**Comment by mfeniseycopes** [comment]
👍
