### ISSUE TITLE
PA Review: Posts

### ISSUE THREAD

**Issue by gtigas** [gtigas/farcebook#29]

**Comment by mfeniseycopes** [comment]
Nice! Just a few things:

- [x] Comments should submit on 'Enter' keypress
- [x] Remove default `outline` from comment input field
- [x] The `x` to delete comments keeps hiding from me
- [x] "Like" button on post should say "Unlike" after liking

**Comment by gtigas** [comment]
@mfeniseycopes ✔️✔️✔️✔️

**Comment by mfeniseycopes** [comment]
👍 

This was also a review of comments, so closing that issue as well.

Closes #30.
